pipeline {
    agent any

    parameters {
        string(name: 'DOCKER_USER', defaultValue: 'yourdockerhubusername', description: 'Docker Hub Username')
        password(name: 'DOCKER_PASS', description: 'Docker Hub Token/Password (masked)')
    }

    environment {
        APP_NAME  = "flashshield-api"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Code Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push to Registry') {
            steps {
                sh '''
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                docker build -t ${DOCKER_USER}/${APP_NAME}:${IMAGE_TAG} -t ${DOCKER_USER}/${APP_NAME}:latest ./app
                docker push ${DOCKER_USER}/${APP_NAME}:${IMAGE_TAG}
                docker push ${DOCKER_USER}/${APP_NAME}:latest
                docker logout
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                sed -i "s|image: flashshield-api:latest|image: ${DOCKER_USER}/${APP_NAME}:${IMAGE_TAG}|g" k8s/03-api-deployment.yaml
                kubectl apply -f k8s/00-namespace.yaml
                kubectl apply -f k8s/01-redis.yaml
                kubectl apply -f k8s/02-postgres-pgbouncer.yaml
                kubectl apply -f k8s/03-api-deployment.yaml
                kubectl apply -f k8s/04-hpa.yaml
                kubectl apply -f k8s/05-ingress.yaml
                kubectl rollout status deployment/flashshield-api -n flashshield --timeout=90s
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
